name: Convert CSV to Capture

on:
  push:
    branches: [main]

jobs:
  convert:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: 3.11
      - name: Install dependencies
        run: pip install pandas
      - name: Run conversion script
        run: python convert.py
      - name: Upload converted file
        uses: actions/upload-artifact@v4
        with:
          name: converted-csv
          path: capture_patch_export.csv
